#!/bin/bash
# Increase swap size on Raspberry Pi Debian Trixie
# This script configures rpi-swap to use a larger swap file
#
# Usage: sudo ./scripts/increase-swap.sh [SIZE_IN_MB]
# Example: sudo ./scripts/increase-swap.sh 2048  (for 2GB swap)

set -euo pipefail

# Default to 2GB if no size specified
SWAP_SIZE_MB="${1:-2048}"

echo "=========================================="
echo "Increasing swap to ${SWAP_SIZE_MB}MB on Raspberry Pi Trixie"
echo "=========================================="
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "Error: This script must be run as root (use sudo)"
    exit 1
fi

# Check if we're on Trixie (rpi-swap) or older (dphys-swapfile)
if command -v rpi-swap >/dev/null 2>&1 || [ -f /etc/rpi/swap.conf ]; then
    echo "Detected rpi-swap (Trixie/Bookworm+)"
    SWAP_SYSTEM="rpi-swap"
elif [ -f /etc/dphys-swapfile ]; then
    echo "Detected dphys-swapfile (older Raspberry Pi OS)"
    SWAP_SYSTEM="dphys-swapfile"
else
    echo "Warning: Could not detect swap system. Attempting rpi-swap configuration..."
    SWAP_SYSTEM="rpi-swap"
fi

if [ "$SWAP_SYSTEM" = "rpi-swap" ]; then
    echo ""
    echo "Configuring rpi-swap for ${SWAP_SIZE_MB}MB swap file..."
    
    # Install rpi-swap if not already installed
    if ! command -v rpi-swap >/dev/null 2>&1 && ! [ -f /etc/rpi/swap.conf ]; then
        echo "Installing rpi-swap..."
        apt-get update -qq
        apt-get install -y rpi-swap
    fi
    
    # Create configuration directory if it doesn't exist
    mkdir -p /etc/rpi/swap.conf.d
    
    # Create swap configuration file
    CONFIG_FILE="/etc/rpi/swap.conf.d/80-increase-swap.conf"
    echo "Creating configuration file: ${CONFIG_FILE}"
    cat > "$CONFIG_FILE" <<EOF
# Increased swap configuration for package builds
# Generated by increase-swap.sh

[Main]
Mechanism=swapfile

[File]
FixedSizeMiB=${SWAP_SIZE_MB}
EOF
    
    echo "✓ Configuration file created"
    echo ""
    echo "Configuration:"
    cat "$CONFIG_FILE"
    echo ""
    echo "⚠️  IMPORTANT: You must reboot for the changes to take effect:"
    echo "   sudo reboot"
    echo ""
    echo "After reboot, verify with: free -h"
    
elif [ "$SWAP_SYSTEM" = "dphys-swapfile" ]; then
    echo ""
    echo "Configuring dphys-swapfile for ${SWAP_SIZE_MB}MB swap..."
    
    # Calculate size in bytes (dphys-swapfile uses bytes)
    SWAP_SIZE_BYTES=$((SWAP_SIZE_MB * 1024 * 1024))
    
    # Backup original config
    if [ -f /etc/dphys-swapfile ]; then
        cp /etc/dphys-swapfile /etc/dphys-swapfile.bak
        echo "Backed up original config to /etc/dphys-swapfile.bak"
    fi
    
    # Update swap size
    sed -i "s/^CONF_SWAPSIZE=.*/CONF_SWAPSIZE=${SWAP_SIZE_BYTES}/" /etc/dphys-swapfile
    
    echo "✓ Updated /etc/dphys-swapfile"
    echo ""
    
    # Check if dphys-swapfile service exists before trying to restart
    if systemctl list-unit-files | grep -q "dphys-swapfile.service"; then
        echo "Restarting dphys-swapfile service..."
        systemctl restart dphys-swapfile
        echo "✓ Swap updated"
    else
        echo "⚠️  dphys-swapfile service not found. This system may be using rpi-swap."
        echo "   Please run this script again - it should detect rpi-swap automatically."
        echo "   Or manually configure rpi-swap as shown in the rpi-swap section above."
    fi
    
    echo ""
    echo "Current swap status:"
    free -h
fi

echo ""
echo "=========================================="
echo "Swap configuration complete!"
echo "=========================================="
